### ISSUE TITLE
Feature request: Add a "days" dropdown for inzidenz and impfidenz

### ISSUE THREAD

**Issue by FloEdelmann** [fxedel/vaterstetten-in-zahlen#14]
Right now, only 7-day incidence and 7-day impfidenz are displayed, which is a good default, because those are known and used everywhere.

It might be interesting to see the same data smoothed over a longer time period though. I suggest to add a dropdown (right there in the tile containing those visualizations, e.g. next to the title) where you can choose between 7 days (default) and 14 days. The title and description in the tile have to change accordingly of course.

**Comment by fxedel** [comment]
I suggest for wont-fix. The 7-day averages are already quite smooth and relatively easy to interpret. A 14-day incidence would be naturally twice as big as the 7 day incidence, which makes it hard to compare these numbers and could lead to misunderstandings. Furthermore, averaging over one week makes sense because it removes effects of certain week days (e.g. less reports on sundays), whereas there is no such methodical benefit for 14 days.

Maybe the new Plotly Graphs are already better recognizable than the ggplot graphs?

![image](https://user-images.githubusercontent.com/7782229/163711589-9c7f3029-5a92-4037-92ea-89a6af725c04.png)
![image](https://user-images.githubusercontent.com/7782229/163711605-928b8c0e-3127-430d-82d5-959ec14d9554.png)
